### ISSUE TITLE
waht is id.imagepath.txt?

### ISSUE THREAD

**Issue by cheng321284** [xuchaoxi/video-cnn-feat#4]
Our code assumes the following data organization. We provide the toydata folder as an example.

collection_name
+ VideoData
+ ImageData
+ id.imagepath.txt

**Comment by huangyuhui666** [comment]
Hello, I couldn't found this txt file in the folder. Have you found that?

**Comment by Houangnt** [comment]
how to get it ? i can't find it in VisualSearch folder
